###服务的端口号
server:
  port: 8112
###服务名称，同一个注册中心集群的服务名称一定要相同
spring:
  application:
    name: wybname-eureka
eureka:
  instance:
  ###注册中心ip地址
    hostname: 127.0.0.1
  client:
    service-url:
    ###注册地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #如果是三台以上的话：defaultZone: http://${eureka.instance.hostname}:9112/eureka/,http://${eureka.instance.hostname}:7112/eureka/
      defaultZone: http://${eureka.instance.hostname}:9112/eureka/
    ###因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候要为true）
    #register-with-eureka: false
    register-with-eureka: true
    ###因为自己是注册中心，不需要去检索服务信息,集群的时候为true
    #fetch-registry: false
    fetch-registry: true

  server:
    #测试的时候关闭自我保护机制（就是开发的时候关闭），保证不可用服务及时踢出
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000  #两秒踢出一次




#两台注册中心服务同时启动，只会有一台在工作，另外一台等主注册中心宕机后才会用
#因为在注册过程中，只会保证一台注册中心服务有对应服务信息数据，当8112注册中心宕机后，启动转移同步数据到9112上去
